Fix TypeError: saveFixedRangeProfiles is not a function
Changed incorrect function call from this.saveFixedRangeProfiles()
to this.saveFixedRangeProfilesToStorage() which is the correct function name.

This was causing the settings modal to not open properly.